import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { NextResponse } from 'next/server';

import { getAppEnv, requireSupabaseEnv } from '@/lib/env';

const ALLOWED_NEXT_PREFIXES = ['/coach', '/longevity', '/plan', '/today', '/settings'];

function sanitizeNext(raw: string | null): string {
  if (!raw) return '/coach';
  if (!raw.startsWith('/') || raw.startsWith('//')) return '/coach';
  if (!ALLOWED_NEXT_PREFIXES.some((p) => raw === p || raw.startsWith(`${p}/`))) {
    return '/coach';
  }
  return raw;
}

export async function POST(request: Request) {
  const formData = await request.formData();
  const email = String(formData.get('email') ?? '').trim();
  const next = sanitizeNext(String(formData.get('next') ?? '/coach'));

  if (!email) {
    return NextResponse.json({ error: 'Missing email' }, { status: 400 });
  }

  const { supabaseUrl, supabasePublishableKey } = requireSupabaseEnv();
  const { appUrl } = getAppEnv();
  const baseUrl = (appUrl ?? 'http://localhost:3000').replace(/\/$/, '');
  const emailRedirectTo = `${baseUrl}/auth/callback?next=${encodeURIComponent(next)}`;

  // Use @supabase/ssr (not the plain @supabase/supabase-js client) so the
  // PKCE code_verifier generated by signInWithOtp lands in a cookie. The
  // /auth/callback route reads that cookie via @supabase/ssr's getAll, then
  // calls exchangeCodeForSession to complete the sign-in. Without matching
  // SSR-wired clients on both sides, the verifier never reaches the
  // browser and the callback fails with "PKCE code verifier not found".
  const cookieStore = await cookies();
  type CookieToSet = { name: string; value: string; options: Record<string, unknown> };

  const supabase = createServerClient(supabaseUrl, supabasePublishableKey, {
    cookies: {
      getAll: () => cookieStore.getAll(),
      setAll: (cookiesToSet: CookieToSet[]) => {
        cookiesToSet.forEach(({ name, value, options }: CookieToSet) => {
          cookieStore.set({ name, value, ...options });
        });
      },
    },
  });

  const { error } = await supabase.auth.signInWithOtp({
    email,
    options: {
      emailRedirectTo,
      shouldCreateUser: true,
    },
  });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 400 });
  }

  return NextResponse.json({
    ok: true,
    email,
    nextStep: 'Check your email for the magic link. Clicking it will sign you in and bring you back here.',
  });
}
